name: Send Water Reminder Email

on:
  schedule:
    - cron: "0 2-12 * * *"  # Runs at 8:00 AM to 6:00 PM IST (2:00 AM to 12:00 PM UTC) every hour

  workflow_dispatch:  # Allows manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install secure-smtplib  # Added in case your environment doesn't have it

      - name: Run Python script to send email
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python send_email.py
